
package Visualizacion;

import Datos.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;


public class GraficaLineas extends javax.swing.JInternalFrame {

   Connection con= Conexion.getConnection();
    public GraficaLineas() {
        initComponents();
        mostrarGraficaLineas();
    }

    public void mostrarGraficaLineas() {

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    try (Statement statement = con.createStatement();
         ResultSet resultSet = statement.executeQuery("SELECT NOMBRE, COUNT(*) AS CANTIDAD FROM lineas GROUP BY NOMBRE")) {

        while (resultSet.next()) {
            String nombre = resultSet.getString("NOMBRE");
            int cantidad = resultSet.getInt("CANTIDAD");
            dataset.addValue(cantidad, "Cantidad", nombre);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al obtener los datos de la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Cantidad de Elementos por Línea", 
            "Línea",                             
            "Cantidad",                          
            dataset                              
    );

    
    chart.setBackgroundPaint(Color.lightGray);

    chart.getCategoryPlot().getRenderer().setSeriesPaint(0, Color.CYAN); 

    ((org.jfree.chart.renderer.category.BarRenderer) chart.getCategoryPlot().getRenderer()).setDrawBarOutline(true);
    ((org.jfree.chart.renderer.category.BarRenderer) chart.getCategoryPlot().getRenderer()).setOutlinePaint(Color.black);

    ChartPanel chartPanel = new ChartPanel(chart);

    
    chartPanel.setPreferredSize(jPanel1.getSize());

    jPanel1.setLayout(new java.awt.BorderLayout());
    jPanel1.add(chartPanel, java.awt.BorderLayout.CENTER);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(50, 130, 181));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
