
package Visualizacion;

import Datos.Conexion;
import Datos.Dinventario;
import Datos.Dprove;
import Datos.Dreci;
import Logica.LProvee;
import Logica.Linventario;
import Logica.Lreci;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Recibos extends javax.swing.JInternalFrame {

    Connection con= Conexion.getConnection();
    Lreci fn;
  List<Dreci> reciPendientes = new ArrayList<>();
     List<Dreci> editarreci = new ArrayList<>();
     List<Dreci> eliminarreci = new ArrayList<>();
    
    public Recibos() {
        initComponents();
         habilitar(false);
        limpiar();
        txtid.setEnabled(false);
         mostrarBuscar("");
         try {
        con.setAutoCommit(false);
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }
    
     public void habilitar(boolean b) {
        btnnuevo.setEnabled(!b);
        btneditar.setEnabled(!b);
        btnguardar.setEnabled(b);
        btncancelar.setEnabled(b);
        
        txtareas.setEnabled(b);
        txtfecha.setEnabled(b);
        txtper1.setEnabled(b);
        txtper1.setEnabled(b);
    }
    
     public void limpiar() {
        txtid.setText("");
        txtareas.setText("");
        txtfecha.setText("");
        txtper1.setText("");
        txtper2.setText("");
    }
     
     public void mostrarBuscar(String linea){
        DefaultTableModel miModelo;
        Lreci fn= new Lreci(con);
        Dreci dts = new Dreci();
        dts.setPersona1(linea);
        miModelo= fn.mostrarreci(dts);
        trecibos.setModel(miModelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtareas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtper1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtper2 = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trecibos = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(50, 130, 181));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de recibos"));

        jLabel1.setText("ID");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setText("IDAreas");

        jLabel3.setText("Fecha salida");

        jLabel4.setText("Persona que recibe");

        jLabel5.setText("Persona entrega");

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tache.png"))); // NOI18N
        btnsalir.setText("Exit");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btncancelar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnnuevo)
                                        .addGap(66, 66, 66)
                                        .addComponent(btneditar)))
                                .addGap(47, 47, 47)
                                .addComponent(btnguardar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtareas, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtper1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtper2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsalir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnsalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(btneditar)
                    .addComponent(btnguardar))
                .addGap(24, 24, 24)
                .addComponent(btncancelar)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(50, 130, 181));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas de recibos"));

        trecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        trecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trecibosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(trecibos);

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarXD.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneliminar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnbuscar))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiar();
        habilitar(false);
        mostrarBuscar("");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
         limpiar();
        habilitar(true);
        mostrarBuscar("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
         habilitar(true);
         mostrarBuscar("");
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
         if(txtareas.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtareas.requestFocusInWindow();
           return;
       }
       
       if(txtfecha.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtfecha.requestFocusInWindow();
           return;
       }
       if(txtper1.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtper1.requestFocusInWindow();
           return;
       }
       if(txtper2.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtper2.requestFocusInWindow();
           return;
       }
         
        String msg=null;
        if(txtid.getText().equals ("")){
          Dreci dts=new Dreci();
          Lreci fn =new Lreci(con);
          dts.setIDareas(Integer.parseInt(txtareas.getText()));
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         Date fecha = null;
    try {
        fecha = dateFormat.parse(txtfecha.getText());
    } catch (ParseException e) {
        e.printStackTrace();
        // Manejar el error de parseo de la fecha aquí
    }
       dts.setFechasal(fecha);
         dts.setPersona1(txtper1.getText());
          dts.setPersona2(txtper2.getText());
          
          reciPendientes.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Inventario agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);
         
       }else{
           Dreci dts=new Dreci();
           Lreci fn =new Lreci(con);
           dts.setIDreci(Integer.parseInt(txtid.getText()));
          dts.setIDareas(Integer.parseInt(txtareas.getText()));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         Date fecha = null;
     try {
        fecha = dateFormat.parse(txtfecha.getText());
       } catch (ParseException e) {
        e.printStackTrace();
        // Manejar el error de parseo de la fecha aquí
      }
       dts.setFechasal(fecha);
          dts.setPersona1(txtper1.getText());
          dts.setPersona2(txtper2.getText());
         editarreci.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Inventario agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);         
          
       }
        limpiar();
      habilitar(true);
       mostrarBuscar("");
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         if(!txtid.getText().equals("")){
            Dreci dts=new Dreci();
          Lreci fn =new Lreci(con);
            dts.setIDreci(Integer.parseInt(txtid.getText()));        
            eliminarreci.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Recibo a eliminar agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);         
           
        }else{
                JOptionPane.showMessageDialog(rootPane, "Seleccione un proveedor a eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
              }
        limpiar();
        habilitar(false);
        mostrarBuscar("");
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        mostrarBuscar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void trecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trecibosMouseClicked
         int fila=trecibos.getSelectedRow();
        txtid.setText(trecibos.getValueAt(fila, 0).toString());
        txtareas.setText(trecibos.getValueAt(fila, 1).toString());
        txtfecha.setText(trecibos.getValueAt(fila, 2).toString());
        txtper1.setText(trecibos.getValueAt(fila, 3).toString());
        txtper2.setText(trecibos.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_trecibosMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Deseas guardar los cambios?", "Confirmar salida", JOptionPane.YES_NO_CANCEL_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        try {
            Lreci fn = new Lreci(con);
            for (Dreci usuario : reciPendientes) {
                fn.insertarreci(usuario);
            }
            for (Dreci usuario : editarreci) {
                fn.editarreci(usuario);
            }
            for (Dreci usuario : eliminarreci) {
                fn.eliminarrecbi(usuario);
            }

            con.commit();
            JOptionPane.showMessageDialog(rootPane, "Commit realizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);

            reciPendientes.clear();
            editarreci.clear();
            eliminarreci.clear();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error al realizar el commit", "Información", JOptionPane.ERROR_MESSAGE);
        }
    } else if (opcion == JOptionPane.NO_OPTION) {
        try {
            con.rollback();
            JOptionPane.showMessageDialog(rootPane, "Rollback realizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error al realizar el rollback", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }
    dispose();
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trecibos;
    private javax.swing.JTextField txtareas;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtper1;
    private javax.swing.JTextField txtper2;
    // End of variables declaration//GEN-END:variables
}
