/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacion;

import Datos.Conexion;
import Datos.Dusuarios;
import Logica.LUsuarios;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;


/**
 * 
 * @author aspid
 */
public class Usuarios extends javax.swing.JInternalFrame {

     Connection con= Conexion.getConnection();
      LUsuarios fn;
  List<Dusuarios> usuariosPendientes = new ArrayList<>();
     List<Dusuarios> editarusuarios = new ArrayList<>();
     List<Dusuarios> eliminarusuarios = new ArrayList<>();
      
     
    
    public Usuarios() {
       initComponents();
        txtID.setEnabled(false);
        limpiar();
      habilitar(true);
      mostrarBuscar("");
      
       try {
        con.setAutoCommit(false);
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }
  
    public void limpiar(){
        txtID.setText("");
        txtNombre.setText("");
        txtclave.setText("");
        txtconclave.setText("");
        txtusuario.setText("");
        iperfil.setSelectedIndex(0);
    }
    
    public void habilitar(boolean b){
        txtNombre.setEnabled(!b);
        txtclave.setEnabled(!b);
        txtconclave.setEnabled(!b);
        txtusuario.setEnabled(!b);
        iperfil.setEnabled(!b);

        btnNuevo.setEnabled(b);
        btnEditar.setEnabled(b);
        btnguardar.setEnabled(!b);
        btncancelar.setEnabled(!b);
    }
    
    public void mostrarBuscar(String usuario){
        DefaultTableModel miModelo;
        LUsuarios fn= new LUsuarios(con);
        Dusuarios dts = new Dusuarios();
        dts.setUsuario(usuario);
        miModelo= fn.mostrarUsuarios(dts);
        tUsuarios.setModel(miModelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtconclave = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        iperfil = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuarios");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        jLabel3.setText("Usuario");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Clave");

        txtclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Confirmar clave");

        jLabel6.setText("Perfil");

        iperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un perfil", "Administrador", "Empleado" }));

        btnNuevo.setBackground(new java.awt.Color(204, 153, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(204, 153, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(204, 153, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(204, 153, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tache.png"))); // NOI18N
        btnsalir.setText("Exit");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID)
                                    .addComponent(txtNombre)
                                    .addComponent(txtusuario)
                                    .addComponent(txtclave)
                                    .addComponent(txtconclave)
                                    .addComponent(iperfil, 0, 165, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancelar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnsalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtconclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(iperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnguardar)
                    .addComponent(btnEditar)
                    .addComponent(btncancelar))
                .addGap(27, 27, 27)
                .addComponent(btnsalir)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(89, 127, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));

        btnbuscar.setBackground(new java.awt.Color(204, 153, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarXD.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        tUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tUsuarios);

        btneliminar.setBackground(new java.awt.Color(204, 153, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar))
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btneliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclaveActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      limpiar();
      habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
      mostrarBuscar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitar(false);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       if(txtNombre.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtNombre.requestFocusInWindow();
           return;
       }
       
       if(txtusuario.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtusuario.requestFocusInWindow();
           return;
       }
       String clave = new String(txtclave.getPassword());
       String confirma = new String(txtconclave.getPassword());
       if(clave.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtclave.requestFocusInWindow();
           return;
       }
       if(confirma.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtconclave.requestFocusInWindow();
           return;
       }
       if(!clave.equals(confirma)){
           JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coiciden", "Validacion", JOptionPane.WARNING_MESSAGE);
           txtclave.requestFocusInWindow();
           txtclave.setText("");
           txtconclave.setText("");
          
           return;
       }
       if(iperfil.getSelectedIndex()== 0){
           JOptionPane.showMessageDialog(rootPane, "Campo obligatorio", "Validacion", JOptionPane.WARNING_MESSAGE);
           iperfil.requestFocusInWindow();
           return;
       }
        
        String msg=null;
        if(txtID.getText().equals ("")){
          Dusuarios dts=new Dusuarios();
          LUsuarios fn =new LUsuarios(con);
         
          String perfil = String.valueOf(iperfil.getSelectedItem());
          dts.setNombre(txtNombre.getText());
          dts.setUsuario(txtusuario.getText());
          dts.setClave(clave);
          dts.setPerfil(perfil);
          usuariosPendientes.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Usuario agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);
         
       }else{
            Dusuarios dts=new Dusuarios();
          LUsuarios fn =new LUsuarios(con);
          String perfil = String.valueOf(iperfil.getSelectedItem());
          dts.setIDusuarios(Integer.parseInt(txtID.getText()));
          dts.setNombre(txtNombre.getText());
          dts.setUsuario(txtusuario.getText());
          dts.setClave(clave);
          dts.setPerfil(perfil); 
         editarusuarios.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Usuario agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);         
          
       }
        limpiar();
      habilitar(true);
       mostrarBuscar("");
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
       
        limpiar();
      habilitar(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if(!txtID.getText().equals("")){
            Dusuarios dts=new Dusuarios();
          LUsuarios fn=new LUsuarios(con);
            dts.setIDusuarios(Integer.parseInt(txtID.getText()));        
            eliminarusuarios.add(dts);
         JOptionPane.showMessageDialog(rootPane, "Usuario a eliminar agregado a la lista pendiente", "Información", JOptionPane.INFORMATION_MESSAGE);         
           
        }else{
                JOptionPane.showMessageDialog(rootPane, "Seleccione un usuario a eliminar", "Informacion", JOptionPane.ERROR_MESSAGE);
              }
        limpiar();
      habilitar(true);
       mostrarBuscar("");
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tUsuariosMouseClicked
        int fila=tUsuarios.getSelectedRow();
        txtID.setText(tUsuarios.getValueAt(fila, 0).toString());
        txtNombre.setText(tUsuarios.getValueAt(fila, 1).toString());
        txtusuario.setText(tUsuarios.getValueAt(fila, 2).toString());
        txtclave.setText(tUsuarios.getValueAt(fila, 3).toString());
        txtconclave.setText(tUsuarios.getValueAt(fila, 3).toString());
        iperfil.setSelectedItem(tUsuarios.getValueAt(fila, 4).toString());
        
    }//GEN-LAST:event_tUsuariosMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       int opcion = JOptionPane.showConfirmDialog(rootPane, "¿Deseas guardar los cambios?", "Confirmar salida", JOptionPane.YES_NO_CANCEL_OPTION);

    if (opcion == JOptionPane.YES_OPTION) {
        try {
            LUsuarios fn = new LUsuarios(con);
            for (Dusuarios usuario : usuariosPendientes) {
                fn.insertarUsuarios(usuario);
            }
            for (Dusuarios usuario : editarusuarios) {
                fn.editarUsuarios(usuario);
            }
            for (Dusuarios usuario : eliminarusuarios) {
                fn.eliminarUsuarios(usuario);
            }

            con.commit();
            JOptionPane.showMessageDialog(rootPane, "Commit realizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);

            usuariosPendientes.clear();
            editarusuarios.clear();
            eliminarusuarios.clear();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error al realizar el commit", "Información", JOptionPane.ERROR_MESSAGE);
        }
    } else if (opcion == JOptionPane.NO_OPTION) {
        try {
            con.rollback();
            JOptionPane.showMessageDialog(rootPane, "Rollback realizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error al realizar el rollback", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }
    dispose();
    
    }//GEN-LAST:event_btnsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> iperfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tUsuarios;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JPasswordField txtconclave;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
